name             'seatbelts'
maintainer       'Brandon Fulk'
maintainer_email 'bf@the42.com'
license          'All rights reserved'
description      'Installs/Configures uyd seatbelts'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends 'rvm'
depends 'apt'
depends 'database', '2.2.0'
depends 'postgresql'
depends 'oh_my_zsh'
depends 'sudo'
depends 'imagemagick'
depends 'nginx'
depends 'swap'
