# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  
  config.vm.define "uyd-dev", primary: true do |dev|
    dev.vm.box = 'seatbelts-14.04'
    dev.vm.network :forwarded_port, guest: 3000, host: 3036, auto_correct: true
    dev.vm.hostname = "local.uhhyeahdu.de"
    dev.vm.network :private_network, ip: "33.33.33.6"
    dev.vm.synced_folder '../', '/home/vagrant/uyd/current'#, type: 'nfs'
    dev.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
    end
    # all of the
    dev.vm.provision :chef_solo do |chef|
      chef.json = {
        :seatbelts => {
          user: "vagrant",
          rails_env: "development"
        },
        :authorization => {
          :sudo => {
            :users => ['vagrant'],
            :include_sudoers_d => true,
            :passwordless => true
          }
        }
      }

      chef.run_list = [
          "recipe[seatbelts::default]",
          "recipe[seatbelts::packages]",
          "recipe[seatbelts::database]"
      ]
    end
  end

  # Production migration to Digital Ocean
  config.vm.define "uyd-do-pro" do |do_pro|
    do_pro.vm.host_name = "archive.uhhyeahdu.de"
    do_pro.vm.provider :digital_ocean do |provider, override|
      override.ssh.private_key_path = './keys/uyd-do-pro'
      override.vm.box = 'digital_ocean'
      override.vm.box_url = "https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box"
      
      provider.token = ENV['DIGITAL_OCEAN_TOKEN']
      provider.image = 'ubuntu-14-04-x64'
      provider.region = 'nyc2'
      provider.size = '512mb'
    end

    # all of the
    do_pro.vm.provision :chef_solo do |chef|
      chef.json = {
        :seatbelts => {
          user: "ubuntu",
          rails_env: "production"
        },
        :authorization => {
          :sudo => {
            :users => ['ubuntu'],
            :include_sudoers_d => true,
            :passwordless => true
          }
        }
      }

      chef.run_list = [
          "recipe[seatbelts::default]",
          "recipe[seatbelts::packages]",
          "recipe[seatbelts::database]",
          "recipe[seatbelts::webserver]"
      ]
    end

  end

  # Production
  config.vm.define "uyd-pro", primary: true do |pro|
    pro.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
    pro.vm.provider :aws do |aws, override|
      aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
      aws.secret_access_key = ENV['AWS_SECRET_KEY']
      aws.region = "us-west-2"
      aws.instance_type = "t1.micro"
      aws.ami = "ami-6ac2a85a"
      override.ssh.username = "ubuntu"
      override.ssh.private_key_path = "keys/uyd-archive.pem"
      aws.keypair_name = "uyd-archive"
      aws.security_groups = [ 'uyd-appserver' ]
      aws.tags = {
        Name: "uyd-productionserver"
      }
    end
    # all of the
    pro.vm.provision :chef_solo do |chef|
      chef.json = {
        :seatbelts => {
          user: "ubuntu",
          rails_env: "production"
        },
        :authorization => {
          :sudo => {
            :users => ['ubuntu'],
            :include_sudoers_d => true,
            :passwordless => true
          }
        }
      }

      chef.run_list = [
          "recipe[seatbelts::default]",
          "recipe[seatbelts::packages]",
          "recipe[seatbelts::database]",
          "recipe[seatbelts::webserver]"
      ]
    end

  end

  config.vm.hostname = "seatbelts-berkshelf"
  config.vm.box = "ubuntu-14.04-seatbelts"
  config.vm.box_url = "https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vbox.box"
  config.omnibus.chef_version = :latest
  config.vm.boot_timeout = 120
  config.berkshelf.enabled = true 
end
